version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      ORG: khanlab
      NAME: prepdwi
      VERSION: 0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies 
          command: |
            apk add --update make wget
      - run:
          name: Building prepdwi docker container
          command: |
              export DOCKER_NAME=$ORG/$NAME:$VERSION.$CIRCLE_BUILD_NUM
              docker build -t $DOCKER_NAME .
      - run:
          name: Running single shell dwi test
          command: |
              mkdir dwi_singleshell
              wget -qO- https://www.dropbox.com/s/68oez1yhhnqp7z2/dwi_singleshell.tar | tar xv -C dwi_singleshell
              #copy test data to a dummy container
              docker create -v /data --name testdata alpine:3.4 /bin/true
              docker cp dwi_singleshell testdata:/data
              export DOCKER_NAME=$ORG/$NAME:$VERSION.$CIRCLE_BUILD_NUM
              docker run --name testapp -it --volumes-from testdata $DOCKER_NAME /data /out participant --no-bedpost
              #copy output data from dummy container
              docker cp testapp:/out dwi_singleshell_out
              ls *
              test -f dwi_singleshell_out/prepdwi/sub-001/dwi/sub-001_dwi_space-T1w_preproc.nii.gz  
              test -f dwi_singleshell_out/prepdwi/sub-001/dwi/sub-001_dwi_space-T1w_preproc.bvec
              test -f dwi_singleshell_out/prepdwi/sub-001/dwi/sub-001_dwi_space-T1w_preproc.bval
              test -f dwi_singleshell_out/prepdwi/sub-001/dwi/sub-001_dwi_space-T1w_proc-FSL_FA.nii.gz
              test -f dwi_singleshell_out/prepdwi/sub-001/dwi/sub-001_dwi_space-T1w_proc-FSL_V1.nii.gz
              test -f dwi_singleshell_out/prepdwi/sub-001/dwi/sub-001_dwi_space-T1w_brainmask.nii.gz
      - run:
          name: Pushing build to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            export DOCKER_NAME=$ORG/$NAME:$VERSION.$CIRCLE_BUILD_NUM
            docker push $DOCKER_NAME
