version: 2
jobs:
  build:
    docker:
      - image: khanlab/neuroglia-dwi:v1.3.2
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
