version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies 
          command: |
            apk add --update make wget tree
      - run:
          name: Building prepdwi docker container
          command: |
            ls *
            tree
            make docker_build
      - run:
          name: Running tests
          command: echo make test_singleshell
