version: 2
jobs:
  build1:
    docker:
      - image: khanlab/neuroglia-dwi:v1.3.2
    steps:
      - checkout
      - run:
          name: Building prepdwi docker container
          command: make docker_build
      - run:
          name: Running tests
          command: echo make test_singleshell
